language: cpp
matrix:
        include: 
        - os: linux
          dist: xenial
        - os: osx

script:
        - mkdir -p build; cd build
        - cmake ..
        - make
        - make check
