language: cpp
matrix:
        include: 
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
        - os: osx

script:
        - mkdir -p build; cd build
        - cmake ..
        - make
        - make check
